# Generated by Django 5.1.2 on 2024-11-21 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OneTimeDatas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UserAuth', models.CharField(max_length=200)),
                ('UserName', models.CharField(max_length=20)),
                ('UserTeam', models.CharField(max_length=20)),
                ('UserDcId', models.CharField(max_length=200)),
                ('UserPlayer1', models.CharField(max_length=50)),
                ('UserPlayer2', models.CharField(max_length=50)),
                ('UserPlayer3', models.CharField(max_length=50)),
                ('UserPlayer4', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='PerfData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ScrimName', models.CharField(max_length=20)),
                ('ScrimTime', models.TimeField()),
                ('Scrimkill', models.PositiveIntegerField()),
                ('Scrimplacement', models.IntegerField()),
                ('ScrimDate', models.DateField()),
                ('ScrimReason', models.CharField(max_length=200)),
                ('ScrimTotalPoint', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ScrimsData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ScrimsName', models.CharField(max_length=20)),
                ('ScrimsTime', models.TimeField()),
                ('ScrimsRegTime', models.TimeField()),
                ('ScrimsId', models.IntegerField()),
                ('ScrimsOrg', models.CharField(max_length=200)),
                ('ScrimsDate', models.DateField()),
            ],
        ),
    ]
