# Generated by Django 5.1.2 on 2024-11-28 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registration_soft', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Auto_save_Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ScrimName', models.CharField(max_length=20)),
                ('ScrimId', models.CharField(max_length=200)),
                ('ScrimDate', models.DateField()),
                ('ScrimTime', models.TimeField()),
            ],
        ),
    ]
