# Generated by Django 5.1.3 on 2025-01-01 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registration_soft', '0002_auto_save_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='auto_save_data',
            name='ScrimUniqueId',
            field=models.CharField(default='uniqueID', max_length=20),
        ),
    ]
