# Generated by Django 5.1.3 on 2025-01-01 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registration_soft', '0003_auto_save_data_scrimuniqueid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auto_save_data',
            name='ScrimUniqueId',
            field=models.CharField(default='uniqueID', max_length=50),
        ),
    ]
