# Generated by Django 5.1.3 on 2025-01-03 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registration_soft', '0004_alter_auto_save_data_scrimuniqueid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='perfdata',
            old_name='Scrimkill',
            new_name='Scrimkillpoint',
        ),
        migrations.RenameField(
            model_name='perfdata',
            old_name='Scrimplacement',
            new_name='Scrimplacementpoint',
        ),
        migrations.RemoveField(
            model_name='perfdata',
            name='ScrimDate',
        ),
        migrations.RemoveField(
            model_name='perfdata',
            name='ScrimName',
        ),
        migrations.RemoveField(
            model_name='perfdata',
            name='ScrimTime',
        ),
        migrations.AddField(
            model_name='perfdata',
            name='killplayer1',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='perfdata',
            name='killplayer2',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='perfdata',
            name='killplayer3',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='perfdata',
            name='killplayer4',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='perfdata',
            name='ScrimReason',
            field=models.CharField(default='reason not given', max_length=200),
        ),
    ]
