# Generated by Django 5.1.3 on 2025-01-03 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registration_soft', '0005_rename_scrimkill_perfdata_scrimkillpoint_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='onetimedatas',
            name='UserPlayer5',
            field=models.CharField(default='none', max_length=50),
        ),
        migrations.AddField(
            model_name='onetimedatas',
            name='UserPlayer6',
            field=models.CharField(default='none', max_length=50),
        ),
    ]
