# Generated by Django 5.1.3 on 2025-01-07 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registration_soft', '0006_onetimedatas_userplayer5_onetimedatas_userplayer6'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfdata',
            name='killplayer1',
            field=models.CharField(default='not played', max_length=10),
        ),
        migrations.AlterField(
            model_name='perfdata',
            name='killplayer2',
            field=models.CharField(default='not played', max_length=10),
        ),
        migrations.AlterField(
            model_name='perfdata',
            name='killplayer3',
            field=models.CharField(default='not played', max_length=10),
        ),
        migrations.AlterField(
            model_name='perfdata',
            name='killplayer4',
            field=models.CharField(default='not played', max_length=10),
        ),
    ]
