# Generated by Django 5.1.3 on 2025-01-08 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registration_soft', '0007_alter_perfdata_killplayer1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfdata',
            name='ScrimUniqueId',
            field=models.CharField(default='none', max_length=15),
        ),
    ]
