# Generated by Django 5.1.3 on 2025-01-09 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registration_soft', '0008_perfdata_scrimuniqueid'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfdata',
            name='PlayerName1',
            field=models.CharField(default='none', max_length=20),
        ),
        migrations.AddField(
            model_name='perfdata',
            name='PlayerName2',
            field=models.CharField(default='none', max_length=20),
        ),
        migrations.AddField(
            model_name='perfdata',
            name='PlayerName3',
            field=models.CharField(default='none', max_length=20),
        ),
        migrations.AddField(
            model_name='perfdata',
            name='PlayerName4',
            field=models.CharField(default='none', max_length=20),
        ),
    ]
