# Generated by Django 5.1.3 on 2025-01-10 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registration_soft', '0010_perfdata_scrimdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfdata',
            name='ScrimPosition',
            field=models.CharField(default='#24', max_length=10),
        ),
    ]
