# Generated by Django 5.1.3 on 2025-01-10 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registration_soft', '0011_perfdata_scrimposition'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfdata',
            name='ScrimName',
            field=models.CharField(default='not models', max_length=20),
        ),
    ]
