# Generated by Django 5.1.3 on 2025-01-22 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registration_soft', '0014_userlogin_username_alter_userlogin_userpass'),
    ]

    operations = [
        migrations.AddField(
            model_name='auto_save_data',
            name='userUniqueId',
            field=models.CharField(default='not given', max_length=500),
        ),
        migrations.AddField(
            model_name='onetimedatas',
            name='UserUniqueId',
            field=models.CharField(default='not given', max_length=500),
        ),
        migrations.AddField(
            model_name='perfdata',
            name='UserUniqueId',
            field=models.CharField(default='not given', max_length=500),
        ),
        migrations.AddField(
            model_name='scrimsdata',
            name='UserUniqueId',
            field=models.CharField(default='not given', max_length=500),
        ),
        migrations.AddField(
            model_name='userlogin',
            name='userUniqueId',
            field=models.CharField(default='not given', max_length=500),
        ),
    ]
