# Generated by Django 5.1.3 on 2025-01-22 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Registration_soft', '0015_auto_save_data_useruniqueid_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auto_save_data',
            old_name='userUniqueId',
            new_name='UserUniqueId',
        ),
        migrations.RenameField(
            model_name='userlogin',
            old_name='userUniqueId',
            new_name='UserUniqueId',
        ),
    ]
