# Generated by Django 5.1.3 on 2025-01-24 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registration_soft', '0016_rename_useruniqueid_auto_save_data_useruniqueid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrimsdata',
            name='ScrimsUid',
            field=models.CharField(default='not given', max_length=50),
        ),
    ]
